### ISSUE TITLE
views: basic CRUD (UI)

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-communities#206]
See also mockups at https://github.com/inveniosoftware/mockups/blob/master/rdm/communities/Communities.pdf

- [x] Communities frontpage page (i.e. https://zenodo.org/communities/): https://github.com/inveniosoftware/invenio-communities/issues/223
- [x] Community creation page: https://github.com/inveniosoftware/invenio-communities/issues/224
- [x] Communities search page: https://github.com/inveniosoftware/invenio-communities/issues/225
- [x] Community item/landing page
  - [x] Search page: https://github.com/inveniosoftware/invenio-communities/issues/226
  - [x] ~~About page (see `about` field in #203)~~ (moved to next sprint)
  - [x] Settings tab
    - [x] Profile: https://github.com/inveniosoftware/invenio-communities/issues/227
    - [x] Privileges: https://github.com/inveniosoftware/invenio-communities/issues/228
