### ISSUE TITLE
Curation policy and about pages

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-communities#861]
- Curation policy is displayed on the community page right sidebar
- About pages have a dedicated URL (e.g. see [BLR](https://zenodo.org/communities/biosyslit/about))

### Next steps

- [x] Review state of the data fields and actual usage/visits ( @ppanero already working on visits)
- [x]  Design and implement display of the data as new community tab(s) in InvenioRDM (@jennur https://github.com/inveniosoftware/invenio-communities/issues/867)
- [x] Data migration: https://github.com/zenodo/zenodo-rdm/issues/207

### Current

Curation policy:

![Image](https://user-images.githubusercontent.com/1814661/177166557-82bb9fa9-a1d1-451f-899c-f4de8eb12e42.png)

---

About pages:

![Image](https://user-images.githubusercontent.com/1814661/177166401-7330aa87-fb72-4a0f-a701-084a7f2573e9.png)
